name: starry_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - numpy=1.20.3
  - "pymc3<3.10"
  - theano=1.0.5
  - corner
  - jupyterlab
  - tqdm
  - arviz=0.11.0
  - scikit-learn
  - pandas
  - matplotlib
  - scipy
  - h5py
  - netcdf4
  - dill
  - pip
